# Setup
title:        Standard Container Integration Format
tagline:      ""
baseurl:      "/SCI-F"
paginate:     1

# About/contact
author:
  name:       Vanessa Sochat
  url:        http://www.containers-ftw.org/SCI-F

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
