# Setup
title:        Standard Container Integration Format
tagline:      ""
baseurl:      "/SCI-F"
paginate:     1
github:       "https://www.github.com/containers-ftw/SCI-F"

# About/contact
author:
  name:       Singularityware
  url:        https://www.github.com/singularityware

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
